import Head from "next/head";
import Image from "next/image";
import React, { useState } from "react";
import Nav from "../components/UI/navbar";
import Form from "../components/UI/form";
import Footer from "../components/UI/footer";
import "react-toastify/dist/ReactToastify.css";

export default function Home() {
  /* Install Chackra UI search and Include a Navbar
     Then create a form it should include a Date,  */
  // Name
  // Last Name
  // Temperature Reading
  // Email
  // Date
  // initially our form is empty, which we want dynamic fields
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Nav />
      </>
      <Form />

      <Footer />
    </>
  );
}
